### ISSUE TITLE
Renaming a package

### ISSUE THREAD

**Issue by holgerteichgraeber** [JuliaRegistries/General#2770]
I would like to rename my package `ClustForOpt` to `TimeSeriesClustering`. https://github.com/holgerteichgraeber/TimeSeriesClustering.jl 

However, JuliaRegistrator gives me the following when I do `@JuliaRegistrator register`:
`Error while trying to register: Changing package names not supported yet` .

What should I do to rename my package?

This is a crossreference of the same issue in JuliaRegistrator: https://github.com/JuliaRegistries/Registrator.jl/issues/211

**Comment by visr** [comment]
I see one example of a renaming PR, #2438, but it got closed in favour of registering a new package, #2535. I believed the new Pkg design would make renaming possible, since the UUID stays the same?

**Comment by KristofferC** [comment]
Theoretically yes, but since it never got tested properly there is currently (arguably) a bug in Julia package loading code that makes renaming a package break all packages that use the old name.

The package loading code could potentially look in the Project file for the UUID of the renamed package but this doesn't currently happen.

**Comment by holgerteichgraeber** [comment]
Ok, since I would like to rename the package now, I assume I will have to register it as a new package. How do I generate a new uuid?
Can I just run?

> ] generate TimeSeriesClustering

**Comment by DilumAluthge** [comment]
Since #2898 has been merged, can we close this issue?
