### ISSUE TITLE
RegistryCI#master workflow for testing on General

### ISSUE THREAD

**Issue by ericphanson** [JuliaRegistries/General#35514]
I originally proposed this on #pkg-registration in the Julia slack:

> The idea that RegistryCI could break General’s automerge is kinda scary, and while we have integration tests, it’s always a bit of worry that when we bump General we might hit weird edge cases with new package registrations and things could break. Especially because RegistryCI does things like load arbitrary packages, clone git repos, etc, and it can be hard to test every edge case (esp since writing the integration tests isn’t always super easy either).

> So I have an idea: what if we sometimes add another workflow to General’s CI which runs RegistryCI#master but does not write comments or influence merging. Then if we want to test something, we can just run that for a few days and then go through and see if we have any spurious failures before cutting a release.

@DilumAluthge mentioned that we need to ensure it doesn't post a comment or create the `automerge/decision` commit status.

**Comment by ericphanson** [comment]
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token could be useful to remove all but the minimal read-only permissions from that workflow we need for RegistryCI to run in a dry-run/staging mode. That way General can rest assured that the unreleased code won't do anything wonky and mess up the registration process.

**Comment by fredrikekre** [comment]
Feels like this should be done in a separate repo instead?

**Comment by DilumAluthge** [comment]
> Feels like this should be done in a separate repo instead?

We already do that currently (that's what the RegistryCI.jl integration tests do).

The motivation for this issue is that we want to make sure that `RegistryCI#master` doesn't throw any errors when being run on actual General registry PRs, so I think that it has to be done on this repo.

As Eric mentioned, for security reasons, the `RegistryCI#master` jobs will only have access to a `GITHUB_TOKEN` with read-only permissions.

**Comment by fredrikekre** [comment]
The test repo could have a script that mirrors PRs from this repo for testing purposes, no?

**Comment by ericphanson** [comment]
> The test repo could have a script that mirrors PRs from this repo for testing purposes, no?

That sounds OK to me; is it easy to do?

**Comment by DilumAluthge** [comment]
> > The test repo could have a script that mirrors PRs from this repo for testing purposes, no?
> 
> That sounds okay to me; is it easy to do?

Personally this sounds more complicated to me than just running it on General.

And since presumably the test repo will be in the `JuliaRegistries` organization, the jobs will still count against the concurrent jobs limit. (The limit of 20 free concurrent jobs is across an entire organization.)

The way we maintain RegistryCI.jl is that the master branch is stable. Any commit on the master branch is stable enough to make a release from. In particular, code is not merged into the master branch until it passes the integration tests.

So this is our current situation:
1. Make PR to RegistryCI.
2. Ask Bors to merge. Bors runs the unit tests and the integration tests on the PR. If all tests pass, Bors merged the PR into master.
3. We register a new release of RegistryCI from master.
4. We deploy the new release of RegistryCI into production on General.

This is the current situation, and it works very well. However, it doesn't cover one case: the case in which the RegistryCI integration tests pass, but then for some reason RegistryCI breaks in production on real PRs.

In the status quo, if we have this case happen, then AutoMerge will break in production.

With this new staging system, we would do this: 

1. Make PR to RegistryCI.
2. Ask Bors to merge. Bors runs the unit tests and the integration tests on the PR. If all tests pass, Bors merged the PR into master.
3. The read-only "AutoMerge" staging job automatically updates to use the latest RegistryCI master.
3. We observe the staging jobs for a while and make sure that the master branch of RegistryCI does not break in production. If things look good, we register a new release of RegistryCI from master.
4. We deploy the new release of RegistryCI into production on General. We know that it will not break, because we already tested it in staging on General.

I guess my point is that the code we are running in "staging" is exactly the same code that we currently deploy directly to production. What we are suggesting here is that we first deploy to staging, and then deploy to production.

**Comment by DilumAluthge** [comment]
I guess my question is this: what is the advantage of the staging environment living in a different repository than the production environment (which is the General repository).

**Comment by DilumAluthge** [comment]
I'm not opposed to doing staging in a different repo.

We just have to figure out this part:

> The test repo could have a script that mirrors PRs from this repo for testing purposes, no?

To me personally, this sounds like a difficult script to write.
