### ISSUE TITLE
automatic merging guidelines

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaRegistries/General#3673]
These guidelines are intended not as requirements for packages but as very conservative guidelines, which, if your new package or new version of a package meets them, it may be automatically merged.

### New package

1. Normal capitalization
    - name should match `r"^[A-Z]\w*[a-z][0-9]?$"`
        - i.e. starts with a capital letter, ASCII alphanumerics only, ends in lowercase
2. Not too short
    - at least five letters
        - you can register names shorter than this, but doing so requires someone to approve
3. Standard initial version number
    - one of `0.0.1`, `0.1.0`, `1.0.0`
4. Repo URL ends with `/$name.jl.git` where `name` is the package name

### New version

1. Sequential version number
    - if the last version was `1.2.3` then the next can be `1.2.4`, `1.3.0` or `2.0.0`
2. Compat for all dependencies
    - all `[deps]` should also have `[compat]` entries (and Julia itself)
    - `[compat]` entries should have upper bounds
3. Version can be installed
    - given the proposed changes to the registry, can we resolve and install the new version of the package?
4. Version can be loaded
    - once it's been installed (and built?), can we load the code?

**Comment by DilumAluthge** [comment]
Personally, I would like to keep the automerging guidelines as conservative as possible.

The goal (at least as I envision it) is not to automerge every package, but rather to automerge many packages.

The use case that you describe is totally fine, but I think it’s okay to have those PR’s be manually merged.

**Comment by DilumAluthge** [comment]
@oxinabox The other thing we can do in your specific use case is set the compat for DataFrames to something like `0.18.0 <= x < 1.0.0`

**Comment by oxinabox** [comment]
> The use case that you describe is totally fine, but I think it’s okay to have those PR’s be manually merged.

Manually merged the first time.
But after the 15th?
Not so much.

It is fine for packages on slow release cycles,
but when practicing continous delivery of packages with dependencies being concurently devleoped, 
it isn't unreasonable to release every day for a week.

> @oxinabox The other thing we can do in your specific use case is set the compat for DataFrames to something like 0.18.0 <= x < 1.0.0

That is not a legal compat specifier, AFAIK.

Could say: `<=100.0` but that means not allowe a lower bound.
Alos: I think we should ideally not automerge things like that too, since it is probably a typo.

**Comment by DilumAluthge** [comment]
> That is not a legal compat specifier, AFAIK.

It will be at some point. See https://github.com/JuliaLang/Pkg.jl/pull/1232

**Comment by oxinabox** [comment]
Nice for some. Uninteresting to those who want to keep compat with the Julia LTS version.

**Comment by staticfloat** [comment]
Things I need for JLL package merging to be automatic:

* We need `_` to be allowed in package names (because all JLL packages will end in `_jll.jl`)

* Non-standard version numbers; because the JLL package versions are linked to the upstream library version, they'll in general not be a nice number like `1.0.0`, nor be nice, sequential versions. 

My PRs currently come in under `@staticfloat`, but in the future I'll probably change it to be `JuliaCIBot` or something like that.  Perhaps we can special-case PRs that end in `_jll.jl` so that they don't have the same version requirements?

**Comment by DilumAluthge** [comment]
We can hardcode some exceptions for JLL packages.

That being said, I would prefer that we first figure out the automerging for regular packages, get that merged, and make sure it works in production. Once automerging for regular packages has been deployed in production for a while, and we have fixed all of the bugs, then we can open a separate issue for automerging JLL packages? Does that sound like an okay plan?

**Comment by DilumAluthge** [comment]
Also, to make life a little easier, would it be possible for you to use the same title format as Registrator for your pull request?

For example, Registrator pull request titles look like this:
- New package: Foo v1.2.3
- New version: Foo v1.2.3

Could you change the format of your titles to look like this:
- New package: Ncurses_jll.jl v6.1.0+0
- New version: Ncurses_jll.jl v6.1.0+0

Do you think that would be possible? It would make my life much easier when I start working on automerging for JLL packages?

**Comment by staticfloat** [comment]
Yes; is it strictly necessary to disambiguate `New package` vs. `New version`?  Especially since the version requirements for a new JLL package will not be stricter, as they are for normal packages?

**Comment by DilumAluthge** [comment]
Presumably we will keep the existing requirement that new packages have a 3 day waiting period.

**Comment by DilumAluthge** [comment]
@staticfloat I opened an issue specifically dedicated to the automerging of JLL packages: https://github.com/JuliaRegistries/GeneralRegistryCI.jl/issues/6

**Comment by DilumAluthge** [comment]
@StefanKarpinski @fredrikekre What do you think about closing this issue?

Further issues regarding automerge can go here: https://github.com/JuliaRegistries/GeneralRegistryCI.jl/issues
