### ISSUE TITLE
Registration failes due to dependancies not building (that should)

### ISSUE THREAD

**Issue by fremling** [JuliaRegistries/General#44848]
Hi, I hope this is the correct place to post this. I'm trying to register a package https://github.com/fremling/MathLinkExtras.jl using the registration bot.

I'm not entirely sure what goes wrong but it looks like the AtuoMerge has trouble instlling one of the dependencies MathLink
https://github.com/JuliaRegistries/General/pull/44841/checks?check_run_id=3600475048

On row 200 one can read "ERROR: Error building `MathLink`: "
Resulting in the error  on row 260: Error: Was not able to successfully `import` the package
etc...

This feels like an error that I cannot fix.... And at least for me (julia 1.0.5) MathLink (0.3.1) builds fine and works as expected.
I'm wondering if the error has to do with MathLink wanting there to exist a mathematica instance to comunicate with and therefore crashing?

**Comment by DilumAluthge** [comment]
@simonbyrne might be able to help out here.

Worst case, you can ask for a manual merge in the #pkg-registration Slack channel.

**Comment by simonbyrne** [comment]
The problem is that MathLink.jl requires Mathematica or Wolfram Engine to work.

**Comment by DilumAluthge** [comment]
> The problem is that MathLink.jl requires Mathematica or Wolfram Engine to work.

There are a couple different options here.

1. You can make it so that doing `import MathLink` doesn't actually require Mathematics or Wolfram Engine, and the requirement is only checked when you try to use a `MathLink` function. For example, this is what @maleadt has done in the `__init__()` function in CUDA.jl. You can always do `import CUDA`, even if you don't have a GPU. An error is only thrown when you try to use CUDA functionality.
2. You can check for the `JULIA_REGISTRYCI_AUTOMERGE` environment variable, which is set to `true` during AutoMerge jobs. If the value is true, you can choose to bypass the requirement for Mathematica or Wolfram Engine.
3. You can leave it as-is, and just ask for manual merges in the #pkg-registration channel in Slack.

All three are valid options. It's up to you.
