### ISSUE TITLE
Replacing package with new source

### ISSUE THREAD

**Issue by tecosaur** [JuliaRegistries/General#56103]
Hello,

I've seen the FAQ section on changing the repo when a package is transferred to a new owner, but I'm wondering what could be done when a new project wants to replace an old one.

In this instance, non-jedi registered https://github.com/non-Jedi/Org.jl as `Org` in 2019 but hasn't had the time he hoped to spend on it since. I have recently developed https://github.com/tecosaur/Org.jl which has progressed much further, and talking to non-jedi we'd both be happy if my Org.jl replaced his in the registry. 

What would be the best way to accomplish this? I see for transfers a repo URL edit is all that's needed, but here the UUID and git sha for non-jedi's v0.1 wouldn't match. Is v0.1 cached in such a way that this could be switched and I could release v0.2 without any issues?

One hacky way that I'd imagine this works is if:
- I delete my repo
- non-jedi transfers his repo to me
- I add a commit wiping everything
- I cherry-pick all of my commits on top of the repo
- I add a commit changing my UUID to match non-jedi's UUID
- I open a "package transfer" PR changing the repo URL

However, this feels like a last resort to me.

**Comment by non-Jedi** [comment]
You can [merge the two git histories like was done with LightGraphs](https://github.com/JuliaGraphs/Graphs.jl/commit/9a2501948053f60c630caf9d4fb257e689629041). Then all that has to be done on this repo is [changing the repo location](https://github.com/JuliaRegistries/General/pull/46876). This will obviously have fewer potential conflicts than were introduced by the lightgraphs procedure since nobody uses my existing package.

**Comment by tecosaur** [comment]
Thanks for that link, I've ended up doing it in two parts, but I think it's sorted now. For anyone that stumbles across this in future, the git merge flag `--allow-unrelated-histories` came in handy.
