### ISSUE TITLE
Package published but not found

### ISSUE THREAD

**Issue by joaquimg** [JuliaRegistries/General#69488]
I recently published Dualization.jl version 0.5.5 (https://github.com/JuliaRegistries/General/pull/69474#event-7511193830),
but when I try to clone it in a documentation GH action it fails:
https://github.com/joaquimg/BilevelJuMP.jl/actions/runs/3178758001/jobs/5180573331

```
Run julia -e 'using Pkg; Pkg.add(name="Dualization", version="0.5.5")'
  julia -e 'using Pkg; Pkg.add(name="Dualization", version="0.5.5")'
  shell: /usr/bin/bash -e {0}
  env:
    GKSwstype: nul
  Installing known registries into `~/.julia`
       Added registry `General` to `~/.julia/registries/General`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Dualization [191a621a]:
 Dualization [191a621a] log:
 ├─possible versions are: 0.1.0-0.5.4 or uninstalled
 └─restricted to versions 0.5.5 by an explicit requirement — no versions left
```

**Comment by AshlinHarris** [comment]
@joaquimg I'm able to download the package with the following code, so I don't think the issue is with the registry:
```
pkg> activate --temp
pkg> add Dualization@0.5.5
pkg> status
Status `/private/var/folders/67/wm9knv7s357b5v9gm4_5kphw0000gv/T/jl_zs9KzX/Project.toml`
⌃ [191a621a] Dualization v0.5.5
Info Packages marked with ⌃ have new versions available
```
Instead, it is probably due to `Pkg` not being able to find a combination of dependencies that satisfies all your requirements. It looks like your [Project.toml](https://github.com/joaquimg/BilevelJuMP.jl/blob/master/Project.toml) requires Dualization 0.5.6.
